### ISSUE TITLE
Incorrect quotes highlighting

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo-intellij-plugin#33] opened 2022-08-23 10:53 UTC
In this code quotes are highlighted even though afaik they shouldn't be

![image](https://user-images.githubusercontent.com/57731693/186139702-4fc27f2a-4039-4608-be9a-677815c2b917.png)

Same thing happens if I somehow modify the second word here

![image](https://user-images.githubusercontent.com/57731693/186139867-53cdf81d-b5f9-40f2-8f9b-7e6a0cc69bee.png)

But if I modify "Hello" the highlighting becomes correct

![image](https://user-images.githubusercontent.com/57731693/186139930-14660cf2-139e-49a6-8f1b-dba23c5bbe0d.png)

**Comment by yegor256** [comment] 2022-09-08 17:53
@mximp please, help us here

**Comment by yasamprom** [comment] 2022-09-09 11:05
@yegor256 This issue is a duplicate of objectionary/eo-intellij-plugin#19

**Comment by OlesiaSub** [comment] 2022-09-09 11:08
@yasamprom it really is, sorry, didn't notice. I can close it then, but pls fix it :))

**Comment by yegor256** [comment] 2022-09-09 12:50
Duplicate of #19

**Closed by yegor256** 2022-09-09 12:50 UTC
Labels: bug
